# Project Euler  -  Question 2  -  Even Fibonacci Numbers

# Each new term in the Fibonacci sequence is generated by
#  adding the previous two terms. By starting with 1 and 2,
#  the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do
#  not exceed four million, find the sum of the even-valued terms.

# Answer = 4613732

ans = 0  # Variable to hold sum
num1 = 0  # First number
num2 = 1  # Second number

# While the second number is less than 4000000
# This ensures the first number is less after moving
while num2 < 4e6:
    num1, num2 = num2, num1 + num2

    # If the number is eve, add to sum
    if num1 % 2 == 0:
        ans += num1

# Print results
print('The sum is: ' + str(ans))
